# WEEK 2 - Know Your Data

## Dataset Understanding and Initial Inspection

In this week, the dataset is loaded and inspected to understand its
size, structure, attributes, data types and initial data quality.

A First Impression Report will also be generated before data cleaning.

In [12]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

## Loading the Dataset

The raw dataset stored inside the Dataset folder is loaded using Pandas.

In [13]:
df = pd.read_csv("Dataset/social_media_vs_productivity.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [14]:
df.head()

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,8,False,False,4,11,21.927072,6.336688
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,5.103897,0.671519,7,True,True,2,25,0.000000,3.412427
2,32,Male,Finance,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,8.583222,0.624378,0,True,False,3,17,10.322044,2.474944
3,60,Female,Unemployed,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,6.052984,1.204540,1,False,False,0,4,23.876616,1.733670
4,25,Male,IT,NaN,Telegram,66,6.214096,8.868753,NaN,7.0,5.405706,1.876254,1,False,True,1,30,10.653519,9.693060

## Dataset Dimensions

The number of rows and columns in the dataset is checked to understand
the overall size of the data.

In [15]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 30000
Number of columns: 19

## Dataset Attributes

The column names are inspected to understand the different features
available in the dataset.

In [16]:
print("Column Names:\n")

for column in df.columns:
    print(column)

Column Names:

age
gender
job_type
daily_social_media_time
social_platform_preference
number_of_notifications
work_hours_per_day
perceived_productivity_score
actual_productivity_score
stress_level
sleep_hours
screen_time_before_sleep
breaks_during_work
uses_focus_apps
has_digital_wellbeing_enabled
coffee_consumption_per_day
days_feeling_burnout_per_month
weekly_offline_hours
job_satisfaction_score

## Data Types and Dataset Structure

The data type of each attribute is checked to identify numerical,
categorical and boolean features before data cleaning and analysis.

In [17]:
df.dtypes

age                                 int64
gender                                str
job_type                              str
daily_social_media_time           float64
social_platform_preference            str
number_of_notifications             int64
work_hours_per_day                float64
perceived_productivity_score      float64
actual_productivity_score         float64
stress_level                      float64
sleep_hours                       float64
screen_time_before_sleep          float64
breaks_during_work                  int64
uses_focus_apps                      bool
has_digital_wellbeing_enabled        bool
coffee_consumption_per_day          int64
days_feeling_burnout_per_month      int64
weekly_offline_hours              float64
job_satisfaction_score            float64
dtype: object

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   age                             30000 non-null  int64
 1   gender                          30000 non-null  str
 2   job_type                        30000 non-null  str
 3   daily_social_media_time         27235 non-null  float64
 4   social_platform_preference      30000 non-null  str
 5   number_of_notifications         30000 non-null  int64
 6   work_hours_per_day              30000 non-null  float64
 7   perceived_productivity_score    28386 non-null  float64
 8   actual_productivity_score       27635 non-null  float64
 9   stress_level                    28096 non-null  float64
 10  sleep_hours                     27402 non-null  float64
 11  screen_time_before_sleep        27789 non-null  float64
 12  breaks_during_work              30000 non-null  int64
 13  uses_focus_apps                 30000 non-null  bool
 14  has_digital_wellbeing_enabled   30000 non-null  bool
 15  coffee_consumption_per_day      30000 non-null  int64
 16  days_feeling_burnout_per_month  30000 non-null  int64
 17  weekly_offline_hours            30000 non-null  float64
 18  job_satisfaction_score          27270 non-null  float64
dtypes: bool(2), float64(9), int64(5), str(3)
memory usage: 4.5 MB

## Missing Value Inspection

Missing values are identified to understand which attributes contain
incomplete data before the cleaning process.

In [19]:
missing_values = df.isnull().sum()

print("Missing Values in Each Column:\n")
print(missing_values)

Missing Values in Each Column:

age                                  0
gender                               0
job_type                             0
daily_social_media_time           2765
social_platform_preference           0
number_of_notifications              0
work_hours_per_day                   0
perceived_productivity_score      1614
actual_productivity_score         2365
stress_level                      1904
sleep_hours                       2598
screen_time_before_sleep          2211
breaks_during_work                   0
uses_focus_apps                      0
has_digital_wellbeing_enabled        0
coffee_consumption_per_day           0
days_feeling_burnout_per_month       0
weekly_offline_hours                 0
job_satisfaction_score            2730
dtype: int64

In [20]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_report = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage (%)": missing_percentage.round(2)
})

missing_report

                                Missing Values  Missing Percentage (%)
age                                          0                    0.00
gender                                       0                    0.00
job_type                                     0                    0.00
daily_social_media_time                   2765                    9.22
social_platform_preference                   0                    0.00
number_of_notifications                      0                    0.00
work_hours_per_day                           0                    0.00
perceived_productivity_score              1614                    5.38
actual_productivity_score                 2365                    7.88
stress_level                              1904                    6.35
sleep_hours                               2598                    8.66
screen_time_before_sleep                  2211                    7.37
breaks_during_work                           0                    0.00
uses_focus_apps                              0                    0.00
has_digital_wellbeing_enabled                0                    0.00
coffee_consumption_per_day                   0                    0.00
days_feeling_burnout_per_month               0                    0.00
weekly_offline_hours                         0                    0.00
job_satisfaction_score                    2730                    9.10

## Duplicate Record Check

Duplicate records are checked to identify repeated observations that may
affect the accuracy of the analysis.

In [21]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

### Observation

The dataset contains no duplicate records. Therefore, duplicate removal
is not required at this stage.

## First Impression Report

The First Impression Report summarizes the initial condition of the dataset
before any cleaning is performed.

It includes dataset size, data types, missing values, duplicate records
and basic statistical information.

In [22]:
print("========== FIRST IMPRESSION REPORT ==========")

print("\nDataset Shape:")
print(df.shape)

print("\nTotal Number of Missing Values:")
print(df.isnull().sum().sum())

print("\nNumber of Duplicate Rows:")
print(df.duplicated().sum())

print("\nData Type Distribution:")
print(df.dtypes.value_counts())

print("\nBasic Statistical Summary:")
display(df.describe())

========== FIRST IMPRESSION REPORT ==========

Dataset Shape:
(30000, 19)

Total Number of Missing Values:
16187

Number of Duplicate Rows:
0

Data Type Distribution:
float64    9
int64      5
str        3
bool       2
Name: count, dtype: int64

Basic Statistical Summary:

,age,daily_social_media_time,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score
count,30000.000000,27235.000000,30000.000000,30000.000000,28386.000000,27635.000000,28096.000000,27402.000000,27789.000000,30000.000000,30000.000000,30000.000000,30000.000000,27270.000000
mean,41.486867,3.113418,59.958767,6.990792,5.510488,4.951805,5.514059,6.500247,1.025568,4.992200,1.999300,15.557067,10.360655,4.964901
std,13.835221,2.074813,7.723772,1.997736,2.023470,1.883378,2.866344,1.464004,0.653355,3.173737,1.410047,9.252956,7.280415,2.121194
min,18.000000,0.000000,30.000000,0.000000,2.000252,0.296812,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,1.639566,55.000000,5.643771,3.757861,3.373284,3.000000,5.493536,0.528490,2.000000,1.000000,8.000000,4.541872,3.363580
50%,41.000000,3.025913,60.000000,6.990641,5.525005,4.951742,6.000000,6.498340,1.006159,5.000000,2.000000,16.000000,10.013677,4.951049
75%,53.000000,4.368917,65.000000,8.354725,7.265776,6.526342,8.000000,7.504143,1.477221,8.000000,3.000000,24.000000,15.300809,6.581323
max,65.000000,17.973256,90.000000,12.000000,8.999376,9.846258,10.000000,10.000000,3.000000,10.000000,10.000000,31.000000,40.964769,10.000000

## Week 2 Summary

- The dataset was successfully loaded and inspected.
- The dataset contains 30,000 rows and 19 columns.
- Numerical, categorical and boolean attributes were identified.
- Missing values were found in several numerical attributes.
- No duplicate records were detected.
- Basic descriptive statistics were generated.
- The identified data-quality issues will be handled in Week 3.